server:
  port: 8091


spring:
  application:
    name: dubbo-samples-consumer-springCloud
  profiles:
    include: [test]

dubbo:
  registry:
    address:  ${dubbo.zookeeper.host}
    timeout: 10000
  protocol:
    name: dubbo
    serialization: hessian2

#  scan:
#    base-packages: com.dubbo.service
logging:
  level:
    root: INFO
  log-path: /data/dubboStress/consumer