server:
  port: 8091
  tomcat:
    max-threads: 1000
    max-connections: 10000
    accept-count: 2000

spring:
  application:
    name: dubbo-samples-consumer-springCloud

dubbo:
  registry:
    address: zookeeper://10.131.32.26:2181
    timeout: 10000
  protocol:
    name: dubbo
  application:
    name: dubbo-samples-consumer-springCloud
#    threads: 5000
#    corethreads: 5000
#  consumer:
#    actives: 3000

#  scan:
#    base-packages: com.dubbo.service