management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    db:
      enabled: false

spring:
  config:
    import: application-dev.yaml

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
