server:
  port: 8090
#  tomcat:
#    max-connections: 20000
#    accept-count: 5000
#    threads:
#      max: 5000


spring:
  application:
    name: dubbo-samples-privider-springCloud
  profiles:
    include: [test]

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: ${dubbo.zookeeper.host}
    timeout: 2000
#    protocol: -1
#    port: -1
#  metadata-report:
#    address: zookeeper://127.0.0.1:2181
#    protocol: -1
#    port: -1
#    default: false
  protocol:
    name: dubbo
    port: 20890
    serialization: hessian2
#    threads: 500
    dispatcher: message
  scan:
    base-packages: com.dubbo.service
#  provider:
#    executes: 6000
#    actives: 6000
